FROM apache/kyuubi:1.10.0-spark

# Copy configuration directories into the container image.
# This copies your local files into the image, leaving the original files in the base image intact.
COPY kyuubi-conf /opt/kyuubi/conf
COPY spark-conf /opt/spark/conf
COPY warehouse /opt/kyuubi/warehouse
COPY delta-jars /opt/spark/jars
COPY delta-jars/hive-jdbc-3.1.3.jar /opt/kyuubi/lib/hive-jdbc-3.1.3.jar
