version: 1
authorization:
  bearerToken: "dapi0123456789"
server:
  host: "0.0.0.0"
  port: 80
shares:
  - name: "default_share"
    schemas:
      - name: "default"
        tables:
          - name: "shared_employees"
            location: "s3a://wba/warehouse/shared_employees"
storage:
  type: "s3"
  root: "s3a://wba/warehouse"
  options:
    endpoint: "http://minio:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    path_style_access: true